/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Polygon9Image from 'src/assets/images/CreditCard_polygon9.png';
import Path11Image from 'src/assets/images/CreditCard_path11.png';
import Path13Image from 'src/assets/images/CreditCard_path13.png';
import Path15Image from 'src/assets/images/CreditCard_path15.png';
import Path17Image from 'src/assets/images/CreditCard_path17.png';
import UnionImage from 'src/assets/images/CreditCard_Union.png';
import UntitledDesign3RemovImage from 'src/assets/images/CreditCard_Untitled_design__3__removebg_preview_1.svg';
import { styled } from '@mui/material/styles';
import { CreditCardProps } from 'src/types';

const CreditCard1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `216px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle16: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(251, 244, 235, 1)`,
  boxShadow: `0px 1px 1px rgba(217, 140, 51, 0.05), 0px 0px 1px rgba(217, 140, 51, 1)`,
  borderRadius: `12px`,
  width: `344px`,
  height: `216px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const VisaIncLogo1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `84px`,
  height: `28px`,
  left: `240px`,
  top: `168px`,
  overflow: `hidden`,
});

const G4158: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `84px`,
  height: `28px`,
  left: `0px`,
  top: `0px`,
});

const Polygon9: any = styled('img')({
  height: `27.1px`,
  width: `11.06px`,
  position: `absolute`,
  left: `30px`,
  top: `0px`,
});

const Path11: any = styled('img')({
  height: `28px`,
  width: `20.41px`,
  position: `absolute`,
  left: `41px`,
  top: `0px`,
});

const Path13: any = styled('img')({
  height: `27.1px`,
  width: `24.42px`,
  position: `absolute`,
  left: `60px`,
  top: `0px`,
});

const Path15: any = styled('img')({
  height: `27.08px`,
  width: `24px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const Path17: any = styled('img')({
  height: `14.74px`,
  width: `16.52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame121: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `38px`,
  top: `144px`,
});

const Q: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(240, 209, 173, 1)`,
  fontStyle: `normal`,
  fontFamily: `JetBrains Mono`,
  fontWeight: `400`,
  fontSize: `8px`,
  letterSpacing: `-0.2px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Q9303: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(174, 112, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `JetBrains Mono`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px 0px 0px 12px`,
}));

const NeerajChinwan: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(174, 112, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `JetBrains Mono`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `36px`,
  top: `118px`,
}));

const Rectangle18: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(247, 232, 214, 1)`,
  borderRadius: `8px`,
  width: `53px`,
  height: `43px`,
  position: `absolute`,
  left: `36px`,
  top: `59px`,
}));

const Line7: any = styled('div')({
  border: `2px solid rgba(255, 255, 255, 1)`,
  width: `43px`,
  height: `0px`,
  position: `absolute`,
  left: `73px`,
  top: `80px`,
});

const Line10: any = styled('div')({
  border: `2px solid rgba(255, 255, 255, 1)`,
  width: `16px`,
  height: `0px`,
  position: `absolute`,
  left: `68px`,
  top: `87px`,
});

const Line13: any = styled('div')({
  border: `2px solid rgba(255, 255, 255, 1)`,
  width: `16px`,
  height: `0px`,
  position: `absolute`,
  left: `105px`,
  top: `87px`,
});

const Line11: any = styled('div')({
  border: `2px solid rgba(255, 255, 255, 1)`,
  width: `16px`,
  height: `0px`,
  position: `absolute`,
  left: `68px`,
  top: `73px`,
});

const Union: any = styled('img')({
  height: `29px`,
  width: `16px`,
  position: `absolute`,
  left: `73px`,
  top: `73px`,
});

const Frame60: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 0px 47px`,
  boxSizing: `border-box`,
  width: `107px`,
  left: `217px`,
  top: `20px`,
});

const UntitledDesign3Remov: any = styled('img')({
  height: `auto`,
  width: `72px`,
  objectFit: `cover`,
  margin: `0px`,
});

function CreditCard(props: CreditCardProps): JSX.Element {
  return (
    <CreditCard1 className={props.className}>
      <Rectangle16></Rectangle16>
      <VisaIncLogo1>
        <G4158>
          <Polygon9 src={Polygon9Image} loading="lazy" alt={'polygon9'} />
          <Path11 src={Path11Image} loading="lazy" alt={'path11'} />
          <Path13 src={Path13Image} loading="lazy" alt={'path13'} />
          <Path15 src={Path15Image} loading="lazy" alt={'path15'} />
          <Path17 src={Path17Image} loading="lazy" alt={'path17'} />
        </G4158>
      </VisaIncLogo1>
      <Frame121>
        <Q>{`● ● ● ●   ● ● ● ●   ● ● ● ●`}</Q>
        <Q9303>{`9303`}</Q9303>
      </Frame121>
      <NeerajChinwan>{`Neeraj Chinwan`}</NeerajChinwan>
      <Rectangle18></Rectangle18>
      <Line7></Line7>
      <Line10></Line10>
      <Line13></Line13>
      <Line11></Line11>
      <Union src={UnionImage} loading="lazy" alt={'Union'} />
      <Frame60>
        <UntitledDesign3Remov
          src={UntitledDesign3RemovImage}
          loading="lazy"
          alt={'Untitled_design__3_-removebg-preview 1'}
        />
      </Frame60>
    </CreditCard1>
  );
}

export default CreditCard;
