/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import TopographyImage from 'src/assets/images/Miles_Topography.png';
import HeroiconsMiniSparkleImage from 'src/assets/images/Miles_heroicons_mini_sparkles.svg';
import { styled } from '@mui/material/styles';
import { MilesProps } from 'src/types';

const Miles1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(241, 243, 245, 1)`,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  height: 'auto',
}));

const Topography: any = styled('img')({
  height: `150px`,
  width: `352px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame180: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame92: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame187: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame189: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(251, 244, 235, 1)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const HeroiconsMiniSparkle: any = styled('img')({
  height: `auto`,
  width: `15px`,
  margin: `0px`,
});

const Miles2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const Get2MilesPer1Spent: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(173, 181, 189, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  margin: `4px 0px 0px 0px`,
}));

const Q6178: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame181: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Rectangle19: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `23px`,
  margin: `0px`,
}));

const Rectangle20: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle21: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `10px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle22: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `4px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle23: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `26px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle24: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `1px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle25: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `1px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle26: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `40px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle27: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle28: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `10px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle29: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle30: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `23px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle31: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `8px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle32: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `1px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle33: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `26px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle34: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `13px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle35: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `32px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle36: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle37: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `8px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle38: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `4px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle39: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle40: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `26px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle41: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `8px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle42: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `1px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle43: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `20px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle44: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `8px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle45: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `32px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle46: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `26px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle47: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `8px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle48: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `32px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle49: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `12px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

const Rectangle50: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(225, 163, 92, 1)`,
  borderRadius: `1px 1px 0px 0px`,
  width: `5px`,
  height: `26px`,
  margin: `0px 0px 0px 4.650000095367432px`,
}));

function Miles(props: MilesProps): JSX.Element {
  return (
    <Miles1 className={props.className}>
      <Topography src={TopographyImage} loading="lazy" alt={'Topography'} />
      <Frame180>
        <Frame92>
          <Frame187>
            <Frame189>
              <HeroiconsMiniSparkle
                src={HeroiconsMiniSparkleImage}
                loading="lazy"
                alt={'heroicons-mini/sparkles'}
              />
            </Frame189>
            <Miles2>{`Miles`}</Miles2>
          </Frame187>
          <Get2MilesPer1Spent>{`Get 2 miles per $1 spent`}</Get2MilesPer1Spent>
        </Frame92>
        <Q6178>{`6,178`}</Q6178>
      </Frame180>
      <Frame181>
        <Rectangle19></Rectangle19>
        <Rectangle20></Rectangle20>
        <Rectangle21></Rectangle21>
        <Rectangle22></Rectangle22>
        <Rectangle23></Rectangle23>
        <Rectangle24></Rectangle24>
        <Rectangle25></Rectangle25>
        <Rectangle26></Rectangle26>
        <Rectangle27></Rectangle27>
        <Rectangle28></Rectangle28>
        <Rectangle29></Rectangle29>
        <Rectangle30></Rectangle30>
        <Rectangle31></Rectangle31>
        <Rectangle32></Rectangle32>
        <Rectangle33></Rectangle33>
        <Rectangle34></Rectangle34>
        <Rectangle35></Rectangle35>
        <Rectangle36></Rectangle36>
        <Rectangle37></Rectangle37>
        <Rectangle38></Rectangle38>
        <Rectangle39></Rectangle39>
        <Rectangle40></Rectangle40>
        <Rectangle41></Rectangle41>
        <Rectangle42></Rectangle42>
        <Rectangle43></Rectangle43>
        <Rectangle44></Rectangle44>
        <Rectangle45></Rectangle45>
        <Rectangle46></Rectangle46>
        <Rectangle47></Rectangle47>
        <Rectangle48></Rectangle48>
        <Rectangle49></Rectangle49>
        <Rectangle50></Rectangle50>
      </Frame181>
    </Miles1>
  );
}

export default Miles;
