/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ReadOnlyFormItem from 'src/components/ReadOnlyFormItem/ReadOnlyFormItem';
import { ReadOnlyFormProps } from 'src/types';

const ReadOnlyForm1: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const ReadOnlyFormItem1: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `0px`,
}));

const Line3: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem2: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line12: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem3: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `12px 0px 0px 0px`,
}));

const Line4: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem4: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line5: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem5: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line6: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem6: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line7: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem7: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line8: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem8: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line9: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem9: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line10: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem10: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

const Line11: any = styled('div')({
  border: `1px solid rgba(241, 243, 245, 1)`,
  alignSelf: `stretch`,
  height: `0px`,
  margin: `12px 0px 0px 0px`,
});

const ReadOnlyFormItem11: any = styled(ReadOnlyFormItem)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `22px`,
  margin: `12px 0px 0px 0px`,
}));

function ReadOnlyForm(props: ReadOnlyFormProps): JSX.Element {
  return (
    <ReadOnlyForm1 className={props.className}>
      <ReadOnlyFormItem1 />
      <Line3></Line3>
      <ReadOnlyFormItem2 />
      <Line12></Line12>
      <ReadOnlyFormItem3 />
      <Line4></Line4>
      <ReadOnlyFormItem4 />
      <Line5></Line5>
      <ReadOnlyFormItem5 />
      <Line6></Line6>
      <ReadOnlyFormItem6 />
      <Line7></Line7>
      <ReadOnlyFormItem7 />
      <Line8></Line8>
      <ReadOnlyFormItem8 />
      <Line9></Line9>
      <ReadOnlyFormItem9 />
      <Line10></Line10>
      <ReadOnlyFormItem10 />
      <Line11></Line11>
      <ReadOnlyFormItem11 />
    </ReadOnlyForm1>
  );
}

export default ReadOnlyForm;
