/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import TopographyImage from 'src/assets/images/RedeemMilesModal_Topography.png';
import HeroiconsMiniSparkleImage from 'src/assets/images/RedeemMilesModal_heroicons_mini_sparkles.svg';
import HeroiconsOutlineXMarImage from 'src/assets/images/RedeemMilesModal_heroicons_outline_x_mark.svg';
import HeroiconsMiniSparkle1Image from 'src/assets/images/RedeemMilesModal_heroicons_mini_sparkles_1.svg';
import HeroiconsOutlineXMar1Image from 'src/assets/images/RedeemMilesModal_heroicons_outline_x_mark_1.svg';
import { styled } from '@mui/material/styles';
import Input1 from 'src/components/Input1/Input1';
import Button1 from 'src/components/Button1/Button1';
import { RedeemMilesModalProps } from 'src/types';

const Property1Default: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(241, 243, 245, 1)`,
  borderRadius: `24px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `40px`,
  boxSizing: `border-box`,
  height: 'auto',
}));

const Topography: any = styled('img')({
  height: `150px`,
  width: `465px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame139: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame124: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame188: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame190: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame189: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(251, 244, 235, 1)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const HeroiconsMiniSparkle: any = styled('img')({
  height: `auto`,
  width: `15px`,
  margin: `0px`,
});

const RedeemYourMiles: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px 0px 0px 12px`,
}));

const HeroiconsOutlineXMar: any = styled('img')({
  height: `auto`,
  width: `24px`,
  margin: `0px`,
});

const LoremIpsumDolorSitAm: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(173, 181, 189, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
}));

const Frame38: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const Frame186: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Input2: any = styled(Input1)(({ theme }: any) => ({
  flex: `1`,
  margin: `0px`,
}));

const Input3: any = styled(Input1)(({ theme }: any) => ({
  flex: `1`,
  margin: `0px 0px 0px 24px`,
}));

const Input4: any = styled(Input1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `24px 0px 0px 0px`,
}));

const Input5: any = styled(Input1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `24px 0px 0px 0px`,
}));

const Input6: any = styled(Input1)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `24px 0px 0px 0px`,
}));

const Frame1241: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const Frame1881: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame1901: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame1891: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(251, 244, 235, 1)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const HeroiconsMiniSparkle1: any = styled('img')({
  height: `auto`,
  width: `15px`,
  margin: `0px`,
});

const RedeemYourMiles1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px 0px 0px 12px`,
}));

const HeroiconsOutlineXMar1: any = styled('img')({
  height: `auto`,
  width: `24px`,
  margin: `0px`,
});

const Frame192: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `40px 0px 0px 0px`,
});

const Frame191: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `385px`,
  margin: `0px`,
});

const YourCurrentMilesBalaSpan1: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
}));

const YourCurrentMilesBalaSpan2: any = styled('span')(({ theme }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
}));

const YourCurrentMilesBala: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(33, 37, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  flex: `1`,
  margin: `0px`,
}));

const Frame381: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `385px`,
  margin: `8px 0px 0px 0px`,
});

const Button2: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px`,
}));

const Input7: any = styled(Input1)(({ theme }: any) => ({
  flex: `1`,
  margin: `0px 0px 0px -1px`,
}));

const Button3: any = styled(Button1)(({ theme }: any) => ({
  margin: `0px 0px 0px -1px`,
}));

const YourNewBalanceWillBe: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(134, 142, 150, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `14px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
}));

const Frame184: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const Button4: any = styled(Button1)(({ theme }: any) => ({
  flex: `1`,
  margin: `0px`,
}));

function RedeemMilesModal(props: RedeemMilesModalProps): JSX.Element {
  return (
    <Property1Default className={props.className}>
      <Topography src={TopographyImage} loading="lazy" alt={'Topography'} />
      <Frame139>
        <Frame124>
          <Frame188>
            <Frame190>
              <Frame189>
                <HeroiconsMiniSparkle
                  src={HeroiconsMiniSparkleImage}
                  loading="lazy"
                  alt={'heroicons-mini/sparkles'}
                />
              </Frame189>
              <RedeemYourMiles>{`Redeem your miles`}</RedeemYourMiles>
            </Frame190>
            <HeroiconsOutlineXMar
              src={HeroiconsOutlineXMarImage}
              loading="lazy"
              alt={'heroicons-outline/x-mark'}
            />
          </Frame188>
          <LoremIpsumDolorSitAm>
            {`Lorem ipsum dolor sit amet consectetur `}
          </LoremIpsumDolorSitAm>
        </Frame124>
        <Frame38>
          <Frame186>
            <Input2 />
            <Input3 />
          </Frame186>
          <Input4 />
          <Input5 />
          <Input6 />
        </Frame38>
        {false && (
          <Frame1241>
            <Frame1881>
              <Frame1901>
                <Frame1891>
                  <HeroiconsMiniSparkle1
                    src={HeroiconsMiniSparkle1Image}
                    loading="lazy"
                    alt={'heroicons-mini/sparkles'}
                  />
                </Frame1891>
                <RedeemYourMiles1>{`Redeem your miles`}</RedeemYourMiles1>
              </Frame1901>
              <HeroiconsOutlineXMar1
                src={HeroiconsOutlineXMar1Image}
                loading="lazy"
                alt={'heroicons-outline/x-mark'}
              />
            </Frame1881>
          </Frame1241>
        )}
        {false && (
          <Frame192>
            <Frame191>
              <YourCurrentMilesBala>
                <YourCurrentMilesBalaSpan1>{`Your current miles balance is `}</YourCurrentMilesBalaSpan1>
                <YourCurrentMilesBalaSpan2>{`6,000.`}</YourCurrentMilesBalaSpan2>
              </YourCurrentMilesBala>
            </Frame191>
            <Frame381>
              <Button2 />
              <Input7 />
              <Button3 />
            </Frame381>
            <YourNewBalanceWillBe>
              {`Your new balance will be 5900.`}
            </YourNewBalanceWillBe>
          </Frame192>
        )}
      </Frame139>
      <Frame184>
        <Button4 />
      </Frame184>
    </Property1Default>
  );
}

export default RedeemMilesModal;
