/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/IconSolidIntegrations_Vector.png';
import { styled } from '@mui/material/styles';
import { IconSolidIntegrationsProps } from 'src/types';

const IconSolidIntegration: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `24px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Vector: any = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `3px`,
  top: `3px`,
});

function IconSolidIntegrations(props: IconSolidIntegrationsProps): JSX.Element {
  return (
    <IconSolidIntegration className={props.className}>
      <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
    </IconSolidIntegration>
  );
}

export default IconSolidIntegrations;
